# Default values for identity.
replicaCount: 1
image: identity:latest
antiAffinity:
  weight: 100
  apps:
    - portal
affinity:
  weight: 100
  apps:
    - iddb
service:
  name: identity
  type: NodePort
  externalPort: 80
  internalPort: 80
livenessProbe:
  path: /status/isalive
  delay: 60
  period: 50
  timeout: 10
readinessProbe:
  command: /status/isready
  delay: 30
  period: 20
  timeout: 5
secrets:
  signingCertificate:
    data: "base64 encoded .pfx file content"
    password: "base64 encoded password to .pfx file"
  google:
    clientId: "base64 encoded value"
    clientSecret: "base64 encoded value"
  portal:
    clientSecret: "base64 encoded value"
  schemesCommander:
    apiSecret: "base64 encoded value"
  schemesQuerier:
    apiSecret: "base64 encoded value"
  owners:
    emailsJsonArray: "[\"base64 encoded\", \"array of owners' emails\"]"
env:
  ASPNETCORE_ENVIRONMENT: Production
  PORTAL_URL: http://midnight-lizard.org
  IDENTITY_URL: http://identity.midnight-lizard.org
  IDENTITY_PORTAL_ACCESS_TOKEN_LIFETIME: 333