kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    iddb: v1
  name: iddb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: iddb-disk
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iddb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      iddb: v1