# Default values for iddb.
replicaCount: 1
image: debezium/postgres:10.0
volumeMountPath: /var/lib/postgresql/data
service:
  name: iddb
  type: NodePort
  externalPort: 5432
  internalPort: 5432
livenessProbe:
  command: [ sh, -c, "exec pg_isready -h $POD_IP" ]
  delay: 60
  period: 50
  timeout: 10
readinessProbe:
  command: [ sh, -c, "exec pg_isready -h $POD_IP" ]
  delay: 30
  period: 20
  timeout: 5
secrets:
  postgres:
    password: "base64 encoded value"
    connection: "base64 encoded value"
env:
  POSTGRES_DB: iddb
  POSTGRES_USER: postgres
  PGUSER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata