apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "name" . }}-schemes-commander-secret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  apiSecret: {{ .Values.secrets.schemesCommander.apiSecret | quote }}