apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "name" . }}-service-secret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  email: {{ .Values.secrets.identityService.email | quote }}
  displayName: {{ .Values.secrets.identityService.displayName | quote }}