apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.antiAffinity.weight }}
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        {{- range .Values.antiAffinity.apps }}
                        - {{ . }}
                        {{- end }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.affinity.weight }}
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        {{- range .Values.affinity.apps }}
                        - {{ . }}
                        {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.delay }}
            periodSeconds: {{ .Values.livenessProbe.period }}
            timeoutSeconds: {{ .Values.livenessProbe.timeout }}
            exec:
              command: {{ .Values.livenessProbe.command }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.delay }}
            periodSeconds: {{ .Values.readinessProbe.period }}
            timeoutSeconds: {{ .Values.readinessProbe.timeout }}
            exec:
              command: {{ .Values.readinessProbe.command }}
          volumeMounts:
            - name: persistent-storage
              mountPath: {{ .Values.volume.mountPath | quote }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "name" . }}-secret
                  key: password
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ template "name" . }}-pvc