apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: identity
  name: identity
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - image: localhost:5000/identity:2
        name: identity
        ports:
          - containerPort: 80
            protocol: TCP
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ENV
          value: prod
        - name: NODE_ENV
          value: production
        - name: PORTAL_URL
          value: http://localhost:7000
        - name: SCHEMES_URL
          value: http://localhost:7001
      restartPolicy: Always
