apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity
  name: identity
spec:
  clusterIP: 10.0.0.30
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: identity
  type: NodePort
